import streamlit as st
from PIL import Image

#st.header('Welcome to FAME E-Project')
st.title('Piezoelectric Energy Harvesting')
st.header('Introduction')

st.write("""Facing current environmental challenges modern solutions are required to ensure sustainable energy production. One of the actualities nowadays includes the replacement of batteries which can be impractical to use on a long period of service by a smaller electronic device powered by ambient energy harvesting. Unlike the batteries, the energy produced by the harvester is not sufficient to power the electric devices directly, therefore the energy is first accumulated in a storage medium such as capacitors and rechargeable batteries [1]. Energy harvesting is reached by converting the mechanical energy triggered by wind or human motion into electrical energy. Several methods to achieve the conversion are studied up to date, among which the **piezoelectric effect**
 has demonstrated a higher energy production and better application to daily-life conditions. Piezoelectric materials can generate electric charge due to their crystalline structure, which allows the re-orientation of molecular dipole moments under applied mechanical stress.""")

st.write("""Four types of piezoelectric materials are available based on their characteristics and properties. These are ceramics, single crystals, polymers, and composites (a combination of single crystal and polymer). Among them, ceramic materials demonstrate higher energy output, although they are more brittle and less stress-resistant than polymers [1]. The most common piezoelectric materials being used today are metal oxides, especially those with the perovskite $ABX_{3}$ structure. PZT (lead zirconate titanate) ceramics have dominated the market for sixty years [2].
Another typical example is PMN-PT (the solid solution of lead magnesium niobate and lead titanate). The new stream of research is to combine piezoelectric materials with pyroelectric (energy conversion from heat) or ferroelectrics (energy conversion from light) for better efficiency and enhanced output [3]. The energy generated by the harvester device depends both on intrinsic (piezoelectric and mechanical properties of selected material, device configuration) and extrinsic (frequency and amplitude of applied stress) properties [1]. 
""")

st.write("""There are some loss mechanisms that need also be considered, along with the potential scale of the system (cm to nm) to make a viable energy harvesting device using these combinations, however, there are three major phases in piezoelectric energy harvesting:""")
st.markdown("1) The mechanical stability of the piezoelectric transducer under large stresses")
st.markdown("2) The mechanical–electrical energy transformation")
st.markdown("3) The efficient utilization of the produced electrical energies within circuitries [2]")

st.write("""We draw inspiration from **Belatchew Arkitekter** who combines these ideas in a sleek strawscraper [4]. By creating $PbTi_{O3}$ nanotubes (PTO NTs) by anodic oxidation and utilizing a hydrothermal approach using $Ti_{O2} nanotubes as a positive template, the Belatchew Architect's strawscrapper concept may be used.
Ti fibers acting as the core electrode linking the individual piezoelectric nanotubes enable the fabrication of flexible, dense, and radially aligned perovskite PTO NTs. By bending or from wind motion in any direction, these free-standing fiber-type nanogenerators produce a consistent quantity of electric power, expanding the range of possible practical applications. Mass production is possible with simple control over the diameter, length, and base materials for various purposes [5].
""")

st.subheader("References")
st.write("""[1] Li, H., Tian, C., & Deng, Z. D. (2014). Energy harvesting from low frequency applications using piezoelectric materials. In Applied Physics Reviews (Vol. 1, Issue 4, p. 041301). AIP Publishing. https://doi.org/10.1063/1.4900845

[2] K. Uchino, “Piezoelectric Energy Harvesting Systems—Essentials to Successful Developments”, Energy Technol. vol. 6, no. 829, 2018 https://doi.org/10.1002/ente.201700785

[3] Bowen, C. R., Kim, H. A., Weaver, P. M., & Dunn, S. (2014). Piezoelectric and ferroelectric materials and structures for energy harvesting applications. Energy Environ. Sci., 7(1), 25–44. https://doi.org/10.1039/c3ee42454e

[4]  “Strawscraper,” Belatchew. [Online]. Available: https://belatchew.com/en/projekt/strawscraper/. [Accessed: 17-Nov-2022]

[5] Gregory, P. (2016, December 19). Any Way the Wind Blows. . .. Advanced Science News. https://www.advancedsciencenews.com/way-wind-blows/ """)

with st.sidebar:
    st.title('Members of Group 6')
    st.header('Masuma Suleymanova - Grenoble INP \n **Website Manager** ')
    image = Image.open('./Media/Masuma_ph.jpg')
    st.image(image, width = None)
    
    st.header('Fatma AbdElKhalek - TU Darmstadt \n **Project Supervisor** ')
    image = Image.open('./Media/fatma_ph.jpg')
    st.image(image, width = None)

    st.header('Zainab Ali - Grenoble INP \n **Project Manager** ')
    image = Image.open('./Media/zainab_ph.jpg')
    st.image(image, width = None)


